"""Add last_briefing_sent_at to user_preferences

Revision ID: 1f6a8c67357e
Revises: e3849dbafbaa
Create Date: 2026-05-30 12:24:54.502099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6a8c67357e'
down_revision: Union[str, Sequence[str], None] = 'e3849dbafbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('last_briefing_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'last_briefing_sent_at')
    # ### end Alembic commands ###
