"""add telegram chat id to preferences

Revision ID: 21504cc8277f
Revises: 7fe327cba2c6
Create Date: 2026-05-22 10:04:55.379686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21504cc8277f'
down_revision: Union[str, Sequence[str], None] = '7fe327cba2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_preferences_telegram_chat_id'), 'user_preferences', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_telegram_chat_id'), table_name='user_preferences')
    op.drop_column('user_preferences', 'telegram_chat_id')
    # ### end Alembic commands ###
