"""add telegram links table

Revision ID: 53468976bef9
Revises: a900da4c849c
Create Date: 2026-05-23 09:22:24.165012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53468976bef9'
down_revision: Union[str, Sequence[str], None] = 'a900da4c849c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_links_code'), 'telegram_links', ['code'], unique=True)
    op.create_index(op.f('ix_telegram_links_user_id'), 'telegram_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_links_user_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_code'), table_name='telegram_links')
    op.drop_table('telegram_links')
    # ### end Alembic commands ###
