"""Add DailyPlan model

Revision ID: 7ac688cde083
Revises: 1f6a8c67357e
Create Date: 2026-07-27 19:13:56.930493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ac688cde083'
down_revision: Union[str, Sequence[str], None] = '1f6a8c67357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('plan_text', sa.Text(), nullable=False),
    sa.Column('time_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('focus_theme', sa.String(length=200), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_plans_plan_date'), 'daily_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_daily_plans_user_id'), 'daily_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_plans_user_id'), table_name='daily_plans')
    op.drop_index(op.f('ix_daily_plans_plan_date'), table_name='daily_plans')
    op.drop_table('daily_plans')
    # ### end Alembic commands ###
